CREATE TABLE IF NOT EXISTS headache (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    type ENUM('MIGRAINE', 'PROVERBIAL', 'PRESSING', 'PULSING', 'DULL', 'SEASONAL') NOT NULL,
    strength INT NOT NULL,
    occurance DATE NOT NULL
);